version: '3.8'

services:
  # Serviço do banco de dados
  db:
    image: postgres:15
    container_name: saude-basica-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - saude-basica-network

  # Serviço do site
  site:
    build: ./site
    container_name: saude-basica-site
    restart: always
    environment:
      FLASK_ENV: development
      DATABASE_URL: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - saude-basica-network

  # Serviço do ETL
  etl:
    build: ./etl
    container_name: saude-basica-etl
    restart: on-failure
    environment:
      DATABASE_URL: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@db:5432/$(POSTGRES_DB)
    volumes:
      - ./etl/data:/etl/data
    depends_on:
      - db
    networks:
      - saude-basica-network

volumes:
  db_data:

networks:
  saude-basica-network:
    driver: bridge
